name: 'Setup Python'
description: 'Setup Python environment'
inputs:
  python-version:
    description: 'Python version to install'
    required: true
    default: '3.10'
runs:
  using: 'composite'
  steps:
    - run: |
        sudo apt-get update
        sudo apt-get install -y python${{ inputs.python-version }}
        sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python${{ inputs.python-version }} 1
        sudo apt-get install -y python3-pip
        python3 -m pip install --upgrade pip
      shell: bash 