name: 'Upload Artifact'
description: 'Upload a build artifact that can be used by subsequent workflow steps'
inputs:
  name:
    description: 'Artifact name'
    required: true
  path:
    description: 'A file, directory or wildcard pattern that describes what to upload'
    required: true
  retention-days:
    description: 'Duration after which artifact will expire in days'
    required: false
    default: '90'
runs:
  using: 'composite'
  steps:
    - run: |
        # Create artifact directory if it doesn't exist
        mkdir -p ${{ inputs.path }}
        
        # Create tar archive
        tar -czf artifact.tar.gz -C ${{ inputs.path }} .
        
        # Upload to GitHub using REST API
        curl -X POST \
          -H "Authorization: token ${{ github.token }}" \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Content-Type: application/octet-stream" \
          --data-binary @artifact.tar.gz \
          "https://api.github.com/repos/${{ github.repository }}/actions/artifacts"
      shell: bash 