name: Instagram Bot

on:
  schedule:
    - cron: '*/30 * * * *'  # 每30分钟运行一次
  repository_dispatch:
    types: [bot-trigger]
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: chiang881/instaBOT/.github/actions/checkout@main
      
    - name: Set up Python
      uses: chiang881/instaBOT/.github/actions/setup-python@main
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run bot
      env:
        INSTAGRAM_USERNAME: ${{ secrets.INSTAGRAM_USERNAME }}
        INSTAGRAM_PASSWORD: ${{ secrets.INSTAGRAM_PASSWORD }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        OPENAI_API_BASE: ${{ secrets.OPENAI_API_BASE }}
        LINGYI_API_KEY: ${{ secrets.LINGYI_API_KEY }}
        LINGYI_API_BASE: ${{ secrets.LINGYI_API_BASE }}
        FIREBASE_CREDENTIALS_BASE64: ${{ secrets.FIREBASE_CREDENTIALS_BASE64 }}
        FIREBASE_DATABASE_URL: ${{ secrets.FIREBASE_DATABASE_URL }}
        CHAT_HISTORY_KEY: ${{ secrets.CHAT_HISTORY_KEY }}
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: python bot.py
        
    - name: Log trigger info
      if: github.event_name == 'repository_dispatch'
      run: |
        echo "Bot triggered from device:"
        echo "IP: ${{ toJson(github.event.client_payload.device_info.ip) }}"
        echo "User Agent: ${{ toJson(github.event.client_payload.device_info.userAgent) }}"
        echo "Platform: ${{ toJson(github.event.client_payload.device_info.platform) }}"
        echo "Language: ${{ toJson(github.event.client_payload.device_info.language) }}"
        echo "Timezone: ${{ toJson(github.event.client_payload.device_info.timezone) }}"
        echo "Timestamp: ${{ toJson(github.event.client_payload.device_info.timestamp) }}"
        
    - name: Upload chat history
      if: always()
      uses: chiang881/instaBOT/.github/actions/upload-artifact@main
      with:
        name: chat-history-${{ github.run_id }}
        path: chat_history/
        retention-days: 90
        
    - name: Clean old artifacts
      if: always()
      uses: chiang881/instaBOT/.github/actions/remove-artifacts@main
      with:
        age: '90 days'
        skip-recent: 5 