name: Instagram Bot

on:
  push:
    branches:
      - main  # 主分支代码推送时触发
  schedule:
    - cron: '0 */3 * * *'  # 每3小时运行一次
  repository_dispatch:
    types: [trigger-bot]  # 添加 repository_dispatch 触发器
  workflow_dispatch:  # 允许手动触发

jobs:
  run-bot:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install cryptography  # 添加加密库
        
    - name: Log trigger info
      if: github.event_name == 'repository_dispatch'
      run: |
        echo "Bot triggered from device:"
        echo "IP: ${{ toJson(github.event.client_payload.device_info.ip) }}"
        echo "User Agent: ${{ toJson(github.event.client_payload.device_info.userAgent) }}"
        echo "Platform: ${{ toJson(github.event.client_payload.device_info.platform) }}"
        echo "Language: ${{ toJson(github.event.client_payload.device_info.language) }}"
        echo "Timezone: ${{ toJson(github.event.client_payload.device_info.timezone) }}"
        echo "Timestamp: ${{ toJson(github.event.client_payload.device_info.timestamp) }}"
        
    - name: Create session file
      run: |
        echo "${{ secrets.INSTAGRAM_SESSION }}" | base64 -d > session.json
      
    - name: Run bot
      run: python bot.py
      env:
        PYTHONUNBUFFERED: 1  # 实时输出日志
        INSTAGRAM_USERNAME: ${{ secrets.INSTAGRAM_USERNAME }}
        INSTAGRAM_PASSWORD: ${{ secrets.INSTAGRAM_PASSWORD }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        OPENAI_API_BASE: ${{ secrets.OPENAI_API_BASE }}
        LINGYI_API_KEY: ${{ secrets.LINGYI_API_KEY }}
        LINGYI_API_BASE: ${{ secrets.LINGYI_API_BASE }}
        CHAT_HISTORY_KEY: ${{ secrets.CHAT_HISTORY_KEY }}  # 添加聊天历史加密密钥
        
    - name: Upload chat history
      if: always()  # 即使任务失败也上传
      uses: actions/upload-artifact@v3
      with:
        name: chat-history-${{ github.run_id }}
        path: chat_history/
        retention-days: 90  # 保存90天
        
    - name: Clean old artifacts
      if: always()
      uses: c-hive/gha-remove-artifacts@v1
      with:
        age: '90 days'  # 删除90天前的artifacts
        skip-recent: 5  # 保留最近5次的artifacts 