name: Instagram Bot

on:
  push:
    branches:
      - main  # 主分支代码推送时触发
  schedule:
    - cron: '0 */3 * * *'  # 每3小时运行一次
  repository_dispatch:
    types: [trigger-bot]  # 添加 repository_dispatch 触发器
  workflow_dispatch:  # 允许手动触发

jobs:
  run-bot:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Create session file
      run: |
        echo "${{ secrets.INSTAGRAM_SESSION }}" | base64 -d > session.json
      
    - name: Run bot
      run: python bot.py
      env:
        PYTHONUNBUFFERED: 1  # 实时输出日志
        INSTAGRAM_USERNAME: ${{ secrets.INSTAGRAM_USERNAME }}
        INSTAGRAM_PASSWORD: ${{ secrets.INSTAGRAM_PASSWORD }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        OPENAI_API_BASE: ${{ secrets.OPENAI_API_BASE }}
        LINGYI_API_KEY: ${{ secrets.LINGYI_API_KEY }}
        LINGYI_API_BASE: ${{ secrets.LINGYI_API_BASE }} 