name: Instagram Bot

# 添加权限限制
permissions:
  actions: none  # 禁止访问 Actions
  checks: none   # 禁止访问检查
  contents: read # 只读代码库内容
  deployments: none
  issues: none
  packages: none
  pull-requests: none
  repository-projects: none
  security-events: none
  statuses: none

on:
  repository_dispatch:
    types: [trigger-bot]  # 添加 repository_dispatch 触发器
  workflow_dispatch:  # 允许手动触发

jobs:
  run-bot:
    runs-on: ubuntu-latest
    
    env:
      LOG_LEVEL: INFO  # 设置日志级别为 INFO，显示详细日志
      INSTAGRAM_USERNAME: ${{ secrets.INSTAGRAM_USERNAME }}
      INSTAGRAM_PASSWORD: ${{ secrets.INSTAGRAM_PASSWORD }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      OPENAI_API_BASE: ${{ secrets.OPENAI_API_BASE }}
      LINGYI_API_KEY: ${{ secrets.LINGYI_API_KEY }}
      LINGYI_API_BASE: ${{ secrets.LINGYI_API_BASE }}
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      FIREBASE_CREDENTIALS_BASE64: ${{ secrets.FIREBASE_CREDENTIALS_BASE64 }}
      FIREBASE_DATABASE_URL: ${{ secrets.FIREBASE_DATABASE_URL }}

    steps:
    - name: Checkout code
      run: |
        git clone https://github.com/chiang881/instaBOT.git .
        git checkout ${{ github.sha }}
        
    - name: Install Python
      run: |
        sudo apt update
        sudo apt install -y python3 python3-pip
        
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install -r requirements.txt
        
    - name: Run bot
      run: |
        python3 bot.py
      
    - name: Log trigger info
      if: github.event_name == 'repository_dispatch'
      run: |
        echo "Bot triggered from device:"
        echo "IP: ${{ toJson(github.event.client_payload.device_info.ip) }}"
        echo "User Agent: ${{ toJson(github.event.client_payload.device_info.userAgent) }}"
        echo "Platform: ${{ toJson(github.event.client_payload.device_info.platform) }}"
        echo "Language: ${{ toJson(github.event.client_payload.device_info.language) }}"
        echo "Timezone: ${{ toJson(github.event.client_payload.device_info.timezone) }}"
        echo "Timestamp: ${{ toJson(github.event.client_payload.device_info.timestamp) }}" 