name: Simple Bot

permissions:
  actions: write  # 允许工作流操作
  checks: write   # 允许检查
  contents: write # 允许读写仓库内容
  deployments: none
  issues: none
  packages: none
  pull-requests: none
  repository-projects: none
  security-events: none
  statuses: write  # 允许更新状态

on:
  workflow_dispatch:  # 允许手动触发

jobs:
  run-bot:
    runs-on: ubuntu-latest
    
    env:
      LOG_LEVEL: DEBUG  # 改为 DEBUG 级别以记录更多信息
      HIDE_CHAT_CONTENT: "false"  # 显示对话内容以便调试
      LINGYI_API_KEY: ${{ secrets.LINGYI_API_KEY }}
      LINGYI_API_BASE: ${{ secrets.LINGYI_API_BASE }}
      FIREBASE_CREDENTIALS_BASE64: ${{ secrets.FIREBASE_CREDENTIALS_BASE64 }}
      FIREBASE_DATABASE_URL: ${{ secrets.FIREBASE_DATABASE_URL }}
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

    steps:
    - name: Checkout code
      run: |
        git clone https://github.com/chiang881/Chronic.git .
        git checkout ${{ github.sha }}
        
    - name: Install Python
      run: |
        sudo apt update
        sudo apt install -y python3 python3-pip
        python3 --version
        pip3 --version
        
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        echo "当前目录文件列表："
        ls -la
        echo "requirements-simple.txt 内容："
        cat requirements-simple.txt
        pip3 install -r requirements-simple.txt
        echo "已安装的包列表："
        pip3 list
        
    - name: Run bot
      run: |
        echo "当前目录文件列表："
        ls -la
        echo "simple_bot.py 内容："
        cat simple_bot.py
        echo "开始运行机器人..."
        python3 -u simple_bot.py  # 添加 -u 参数以确保日志实时输出 