name: 'Remove old artifacts'
description: 'Remove old artifacts from the repository'
inputs:
  age:
    description: 'Minimum age of artifacts to remove'
    required: true
    default: '90 days'
  skip-recent:
    description: 'Number of recent artifacts to keep'
    required: false
    default: '5'
runs:
  using: 'composite'
  steps:
    - run: |
        # Convert age to seconds
        age_seconds=$(echo "${{ inputs.age }}" | sed 's/[^0-9]*//g')
        age_seconds=$((age_seconds * 24 * 60 * 60))
        
        # Get list of artifacts
        artifacts=$(curl -s \
          -H "Authorization: token ${{ github.token }}" \
          -H "Accept: application/vnd.github.v3+json" \
          "https://api.github.com/repos/${{ github.repository }}/actions/artifacts")
        
        # Parse and delete old artifacts
        echo "$artifacts" | jq -r '.artifacts[] | select(.created_at < (now - '"$age_seconds"')) | .id' | \
        head -n -${{ inputs.skip-recent }} | \
        while read artifact_id; do
          curl -X DELETE \
            -H "Authorization: token ${{ github.token }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/actions/artifacts/$artifact_id"
          echo "Deleted artifact $artifact_id"
        done
      shell: bash 